hola = "Manuel"
#|
# DIR - DEVUELVE LA LISTA DE ATRIBUTOS VALIDOS PARA EL OBJETO
# UPPER - CONVIERTE A MAYUSCULA
# CAPITALIZE - PRIMERA EN MAYUCCULA
# FIND - BUSCA LA SUBCADENA Y DEVUELVE SU POSICION 
# INDEX - METODODO QUE ENCUENTRA LA PRIMERA APARICION DEL VALOR ESPECIFICADO, SINO DEVUELVE UNA EXCEPCION
# ISNUMERIC - SI ES NUMERICO DEVUELVE TRUE 
# ISALPHA - SI ES ALFABETICO DEVUELVE TRUE 
# COUNT - CUENTA LAS OCURRENCIAS DE UNA SUBCADENA EN LA CADENA
# LEN - CUENTA LOS CARACTERES DE UNA CADENA
# REPLACE - REEMPLCA UNA CADENA POR OTRA|

#print(hola.replace("Manuel", "Juan"))

# METODOS DE LISTAS 
mi_lista = [1, 2, 3, 10, 4, 5]
#|
# LEN - CUENTA LA CANTIDAD DE ELEMENTOS DE UNA LISTA
# APPEND - AGRAGA UN ELEMNTO A LA LISTA EN EL INDECE ESPECIDICADO
# EXTEND - AGREGA VARIOS ELEMENTOS A LA LISTA
# POP- ELIMINA UN ELEMENTO DE UNA LISTA, PIDE INDICE Y DEVUELVE EL VALOR
# REMOVE - REMUEVE UN ELEMENTO DE UNA LISTA, PIDE EL VALOR 
# CLEAR -  ELIMINA TODOS LOS ELENTOS DE UNA LISTA
# SORT - ORDENA UNA LISTA DE FORMA ASCENDENTE A DESCENDETE
# REVERSE - INVIERTE LOS ELEMBNTOS DE UNA LISTA|#

mi_lista.append(6)
mi_lista.sort()
print(mi_lista)
